Ditto 1521: Initial submission of scoping search fields for things.
eclipse-ditto/ditto pull request #1870
Opened 2024-01-22 20:09 UTC by an1310

Long time coming.

2024-01-23 10:31 UTC, thjaeckle requested changes
Thanks a lot @an1310 for that awesome PR.
Looking already really good - I did a quick round of comments to what I found.

What is still missing before getting merged:
* an "empty" default configuration in the `search.conf` file
   * containing e.g. commented out example of how the config for a concrete namespace would look like
* documentation on how to enable the `SearchIndexingSignalEnrichmentFacadeProvider`, maybe both:
   * in `search.conf` as commented out alternative to the default `DittoCachingSignalEnrichmentFacadeProvider` for `ditto.extensions.caching-signal-enrichment-facade-provider`
   * and as a subsection in the [Operating Ditto](https://eclipse.dev/ditto/installation-operating.html) docs
      * Next to [Restricting entity creation](https://eclipse.dev/ditto/installation-operating.html#restricting-entity-creation)
      * Source is here: [installation-operating.md](https://github.com/eclipse-ditto/ditto/edit/master/documentation/src/main/resources/pages/ditto/installation-operating.md)
      * Similar description as for the "Restricting entity creation"


And one _optional_ wish from me 😁 
I just figured out that the `entity-creation` configuration already supports adding wildcards.
So maybe we could integrate that in the same way, see:
https://github.com/eclipse-ditto/ditto/blob/2a35c6f60d22037f8fa3124806863ec1e5c1a8e6/policies/enforcement/src/main/java/org/eclipse/ditto/policies/enforcement/config/DefaultCreationRestrictionConfig.java#L37-L55

So basically the `getNamespace` would return a `Pattern` instead which is created during the config parsing.

An additional benefit of that would be that is configured commonly as the "Restriction entity creation".

What do you think about that?

2024-01-23 10:35 UTC, thjaeckle commented on thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/common/config/DefaultNamespaceSearchIndexConfig.java
> +     * @param namespace the namespace config passed in the {@code config}.
this `@param namespace` must be removed - there is no parameter named in that way.
That's also why the build currently is failing (due to Javadoc error).

2024-01-23 10:57 UTC, thjaeckle commented on thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/common/config/DefaultNamespaceSearchIndexConfig.java
> +    }
This method is never called.
Propably a leftover from copy&paste - please remove it (also the Javadoc is wrong).

2024-01-23 11:14 UTC, thjaeckle commented
Feature wise it works really great 👍 
I just manually tested and only the defined fields were inserted into the search index, awesome 🏅

2024-01-23 12:49 UTC, an1310 commented on internal/models/signalenrichment/src/main/java/org/eclipse/ditto/internal/models/signalenrichment/SignalEnrichmentCacheKey.java
> +public final class SignalEnrichmentCacheKey implements CacheKey<SignalEnrichmentContext> {
Ah, I missed this in my cleanup.

2024-01-23 12:50 UTC, an1310 commented on thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/starter/config/DittoSearchConfigTest.java
> +        //assertThat(underTest.getSearchIncludeFields().isEmpty()).isTrue();
Old working copy -- I ended up adding a new unit test.

2024-01-23 12:52 UTC, an1310 commented
> Thanks a lot @an1310 for that awesome PR. Looking already really good - I did a quick round of comments to what I found.
> 
> What is still missing before getting merged:
> 
> * an "empty" default configuration in the `search.conf` file
>   
>   * containing e.g. commented out example of how the config for a concrete namespace would look like
> * documentation on how to enable the `SearchIndexingSignalEnrichmentFacadeProvider`, maybe both:
>   
>   * in `search.conf` as commented out alternative to the default `DittoCachingSignalEnrichmentFacadeProvider` for `ditto.extensions.caching-signal-enrichment-facade-provider`
>   * and as a subsection in the [Operating Ditto](https://eclipse.dev/ditto/installation-operating.html) docs
>     
>     * Next to [Restricting entity creation](https://eclipse.dev/ditto/installation-operating.html#restricting-entity-creation)
>     * Source is here: [installation-operating.md](https://github.com/eclipse-ditto/ditto/edit/master/documentation/src/main/resources/pages/ditto/installation-operating.md)
>     * Similar description as for the "Restricting entity creation"
> 
> And one _optional_ wish from me 😁 I just figured out that the `entity-creation` configuration already supports adding wildcards. So maybe we could integrate that in the same way, see:
> 
> https://github.com/eclipse-ditto/ditto/blob/2a35c6f60d22037f8fa3124806863ec1e5c1a8e6/policies/enforcement/src/main/java/org/eclipse/ditto/policies/enforcement/config/DefaultCreationRestrictionConfig.java#L37-L55
> 
> So basically the `getNamespace` would return a `Pattern` instead which is created during the config parsing.
> 
> An additional benefit of that would be that is configured commonly as the "Restriction entity creation".
> 
> What do you think about that?

I think this suggestion is great.  If it's okay, can we do this in a separate issue and I can contribute it?

2024-01-23 13:40 UTC, an1310 commented on thingsearch/service/src/main/java/org/eclipse/ditto/thingsearch/service/persistence/write/streaming/SearchIndexingSignalEnrichmentFacadeProvider.java
> +                JsonFieldSelector indexedFields = JsonFieldSelector.newInstance(pointerString, furtherPointerStrings);
There's a function to create a JsonFieldSelector with an iterable of Strings with JsonParseOptions.  Is that the one you mean?

2024-01-23 13:45 UTC, an1310 commented on thingsearch/service/src/test/java/org/eclipse/ditto/thingsearch/service/common/config/DefaultNamespaceSearchIndexConfigTest.java
> +                                "features/info/other"                        )
When I was researching formatting rules, I followed the example set in the org.eclipse.ditto.gateway.service.util.config.security.DefaultOauthConfigTest.  But I'll make this a bit more inline with everything else.

2024-01-23 16:58 UTC, thjaeckle commented
One TODO to check (I can also check - but maybe you are quicker):
* what happens when you search for a field which is not indexed?
   * do you find nothing (I assume)
   * is there an error (there probably could be - and maybe even should be) indicating that this field is not indexed?

2024-01-24 09:58 UTC, thjaeckle approved these changes
@an1310 I did a review commit, hope you don't mind - providing:
* added a cache to SearchIndexingSignalEnrichmentFacade in order to only evaluate "patterns" once for a given namespace
* removed copy&pasted unit tests in SearchIndexingSignalEnrichmentFacadeTest by adding another abstract test class AbstractCachingSignalEnrichmentFacadeTest
* added a unit test testing selection of JsonFieldSelectors based on different namespaces
* minor cleanup and formatting
* enhanced documentation about how to configure the indexed namespaces via system properties

For me, this would now good to be merged 👍

2024-01-24 11:22 UTC, an1310 commented
I don't mind in the slightest. Glad to have helped.

2024-01-24 12:15 UTC, thjaeckle commented
@an1310 I also just provided configuration via the Helm chart - so that it is easily enabled and configured via `values.yaml`

Once the build is green (nowadays GitLab runners seem quite busy), I will merge :)

Thanks a lot for this contribution - I guess not only you will benefit from that configuration.

2024-01-24 14:42 UTC, merged